[package]
name = "voi-client"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow.workspace = true
cpal = "0.17.3"
eframe = "0.33.3"
env_logger = "0.11.9"
log = "0.4.29"
opus = "0.3.1"
postcard = { version = "1.1.3", features = ["alloc"] }
ringbuf = "0.4.8"
serde = { version = "1.0.228", features = ["derive"] }
tokio.workspace = true
